const chess = [    
    "./img/chess/2.png",
    "./img/chess/2.png",
    "./img/chess/4.png",
    "./img/chess/4.png",
    "./img/chess/6.png",
    "./img/chess/7.png",
    "./img/chess/7.png",
    "./img/chess/7.png",
    "./img/chess/7.png",
    "./img/chess/7.png",
    "./img/chess/7.png",
    "./img/chess/7.png",
    "./img/chess/7.png",
    "./img/chess/9.png",
    "./img/chess/9.png",
    "./img/chess/11.png",

    "./img/chess/b2.png",
    "./img/chess/b2.png",
    "./img/chess/b4.png",
    "./img/chess/b4.png",
    "./img/chess/b6.png",
    "./img/chess/b7.png",
    "./img/chess/b7.png",
    "./img/chess/b7.png",
    "./img/chess/b7.png",
    "./img/chess/b7.png",
    "./img/chess/b7.png",
    "./img/chess/b7.png",
    "./img/chess/b7.png",
    "./img/chess/b9.png",
    "./img/chess/b9.png",
    "./img/chess/b11.png",
]
addDeck("Шахматы","chess", chess, "170px", "120px", 0.5, false);
